create database traductor
go
use traductor 
go

CREATE TABLE [dbo].[TBL_USUARIOS]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [NAME] NVARCHAR(50) NOT NULL
);

CREATE PROCEDURE [dbo].[CRE_CUSTOMER_PR]
	@P_NAME nvarchar(50)
AS
	INSERT INTO [dbo].[TBL_USUARIOS] VALUES(@P_NAME);

CREATE PROCEDURE [dbo].[RET_ALL_USUARIO_PR]
AS
	SELECT ID, NAME FROM TBL_USUARIOS;

CREATE PROCEDURE [dbo].[UPD_USUARIO_PR]
	@P_NAME nvarchar(50)
AS
	UPDATE [dbo].[TBL_USUARIOS] SET NAME=@P_NAME WHERE ID=@P_ID;

CREATE PROCEDURE [dbo].[RET_USUARIO_PR]
	@P_ID nvarchar(25)
AS
	SELECT ID, NAME FROM TBL_USUARIOS WHERE ID=@P_ID;

CREATE PROCEDURE [dbo].[DEL_USUARIO_PR]
	@P_ID INT
AS
	DELETE FROM TBL_USUARIOS WHERE ID=@P_ID;